consul:
  image: 'krmcbride/consul:0.5'
  ports:
  - '8300:8300'
  - '8301:8301'
  - '8301:8301/udp'
  - '8302:8302'
  - '8302:8302/udp'
  - '8400:8400'
  - '8500:8500'
  - '53:53'
  - '53:53/udp'
  volumes:
  - '/var/run/docker.sock:/var/run/docker.sock'
  - '/usr/local/bin/docker:/usr/bin/docker'
  command: -server -bootstrap-expect 1
